# UR5e 碰撞球配置；源自 curobo content/configs/robot/ur5e.yml 内联 collision_spheres
collision_spheres:
  shoulder_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.1
  upper_arm_link:
    - center: [-0.416, -0.0, 0.143]
      radius: 0.078
    - center: [-0.015, 0.0, 0.134]
      radius: 0.077
    - center: [-0.14, 0.0, 0.138]
      radius: 0.062
    - center: [-0.285, -0.001, 0.139]
      radius: 0.061
    - center: [-0.376, 0.001, 0.138]
      radius: 0.077
    - center: [-0.222, 0.001, 0.139]
      radius: 0.061
    - center: [-0.055, 0.008, 0.14]
      radius: 0.07
    - center: [-0.001, -0.002, 0.143]
      radius: 0.08
  forearm_link:
    - center: [-0.01, 0.002, 0.031]
      radius: 0.072
    - center: [-0.387, 0.0, 0.014]
      radius: 0.057
    - center: [-0.121, -0.0, 0.006]
      radius: 0.057
    - center: [-0.206, 0.001, 0.007]
      radius: 0.057
    - center: [-0.312, -0.001, 0.006]
      radius: 0.056
    - center: [-0.057, 0.003, 0.008]
      radius: 0.065
    - center: [-0.266, 0.0, 0.006]
      radius: 0.057
    - center: [-0.397, -0.001, -0.018]
      radius: 0.052
    - center: [-0.164, -0.0, 0.007]
      radius: 0.057
  wrist_1_link:
    - center: [-0.0, 0.0, -0.009]
      radius: 0.047
    - center: [-0.0, 0.0, -0.052]
      radius: 0.047
    - center: [-0.002, 0.027, -0.001]
      radius: 0.045
    - center: [0.001, -0.01, 0.0]
      radius: 0.046
  wrist_2_link:
    - center: [0.0, -0.01, -0.001]
      radius: 0.047
    - center: [0.0, 0.008, -0.001]
      radius: 0.047
    - center: [0.001, -0.001, -0.036]
      radius: 0.047
    - center: [0.001, -0.03, -0.0]
      radius: 0.047
  wrist_3_link:
    - center: [0.001, 0.001, -0.029]
      radius: 0.043
  tool0:
    - center: [0.001, 0.001, 0.05]
      radius: 0.05
